name: Check homework
on: [push]
jobs:
  validate:
    if: ${{ github.repository_owner != 'ktsstudio' }}
    runs-on: ubuntu-latest
    env:
      IMAGE: 'ktshub/frontend-hw-checker:task-35f2af7d-ca70-445a-a839-8365d431bc5c'
    steps:
      - uses: actions/checkout@main
      - run: docker run --entrypoint /bin/bash -e GITHUB_REPOSITORY -e GITHUB_REF --mount src="$(pwd)",target=/go/code/source,type=bind ${{ env.IMAGE }} -c "mv build/main source && cd source && ./main"
